### PR TITLE
move to wwwroot as umbraco will not read that if is not in that path …

### PR DESCRIPTION
**Pull request by bielu**
Hi @KevinJump, 
I noticed funny part on umbraco, if you running that on linux webapp you apparently have to nest app_plugins folder into wwwroot, so there is small pr from me again :)

### CODE REVIEW

**Comment by KevinJump** [comment]
Hi,  doesn't that mean all plugins would have to be in wwwroot/app_plugins (not just uSync) it sounds quite the change (at the Umbraco level not uSync really).

**Comment by bielu** [comment]
@KevinJump I think it is actually more linux related and difference about paths which are differently behaving in linux and windows :)

**Comment by KevinJump** [comment]
yeah but if we bring that change in the app_plugins are no longer where umbraco (on windows anyway) expects them to be, and other things like minification etc won't work. (i think i will have to test).

**Comment by bielu** [comment]
@KevinJump hmmm that is true, and I think it might be worth to mention that issue to Umbraco.

**Comment by KevinJump** [comment]
out of interest what linux platform are you running on ?  - i am thinking i am going to have to get some virtual/hosting somewhere to test all this stuff out very soon

**Comment by bielu** [comment]
@KevinJump I am running that on s1 linux webapp in azure :)

**Comment by bielu** [comment]
@KevinJump I reported bug to Umbraco: https://github.com/umbraco/Umbraco-CMS/issues/11030 lets see what they will say :)

**Comment by KevinJump** [comment]
Hi, I think this was all resolved internally before the release of Umbraco 9 - so i am going to close this PR here, because i don't think we need to do anything ?

**Pull request closed without merging**
