### PR TITLE
update v9 to v10

### PR DESCRIPTION
**Pull request by CarlSargunar**
Changed paths for uSync from v9 to v10, inc config settings and default paths

### CODE REVIEW

**Comment by KevinJump** [comment]
Yeah 

I know i triggered a lot of people by not updating this for v10 😞 

but unfortunately this would now be a breaking change and so is a major update thing 😢 
My fault really should have done it on 10.0 , but if we did it now existing installs would break. 

I think we need to either think of a way to do it for fresh installs but not existing ones - or do it for v11 (and I am wondering if we should drop the version number).

**Comment by KevinJump** [comment]
🤔  One option could be to rename any existing v9 folders to v10 in a migration ?

**Comment by CarlSargunar** [comment]
I did wonder about that, no worries - what about some sort of migration or post installation step?

**Comment by KevinJump** [comment]
yeah - I might play about with migrations see how that feels.

**Comment by CarlSargunar** [comment]
OK - happy to help out if I can in any way :-)

**Comment by timeverts** [comment]
Heh, heh... this caught me out too. I was just about to log a ticket about this being a bug!
Hope you find a nice resolution.

**Pull request closed without merging**
